### PR TITLE
Created base for the blog

### PR DESCRIPTION
**Pull request by btkcodedev**
Added backbone with Reactjs
Added main renderers with three simple sections/comnponents inside
<li>App.js</li>
<li>Index.js</li>
<li>App.test.js</li>
<br>
Components:
<br>
<li>Header
<li>About
<li>Footer
<br>
<br>
Made Mobile responsive
<li>media-queries.css: to handle mobile responsiveness</li>
<li>layout.css: for handling the sections</li>
<li>default.css is from the open source normalise.css</li>
<li>Added Favicon as FOSS Logo
<br>
<br>
Others
<li>Used font awesome for icons</li>
<li>Used https://github.com/lindelof/particles-bg for header background</li>

npm i
npm start 
:to see the result

### CODE REVIEW

**Comment by btkcodedev** [comment]
@AnandBaburajan Thanks Senior, sorry that I've not discussed with the team (@anaswaratrajan @JITHIKASAGAR123 @saleekah1234),  i'll remember it the next time :), but also since they were planning with gatsbyjs as the core which is based on react, I think i've just built a sample code for them(I THINK).
Hope they will not reject it.
Anyways Thanks for the comment, really happy to join with FOSS.

**Comment by AnandBaburajan** [comment]
> since they were planning with gatsbyjs as the core which is based on react, I think i've just built a sample code for them.

Ah, that sounds good! Maintainer, please do "check out" the PR. Also, no need to call any of us seniors: addressing with @  is enough :) Thanks again!

**Comment by anaswaratrajan** [comment]
@btkcodedev Thanks for your PR! :D Unfortunately, we had decided on an apt gatsbyjs boilerplate for the project and won't be able to accept your PR. But, we would love to have you onboard the team! Join the discussions on [gitter](https://gitter.im/FOSS-Cell-GECPKD/foss-blog). Looking forward to your contributions!

**Comment by btkcodedev** [comment]
@anaswaratrajan Fine, Thanks :)

**Pull request closed without merging**
